### ISSUE TITLE
FAILED Deploy to Azure 

### ISSUE THREAD

**Issue by dfinke** [sdras/example-azure-node#1]
# Thank you for the great write up.

Is there a log I can look at on Azure when the `entrypoint.sh` fails?

I ran the `entrypoint.sh` `az cli` commands on my local machine, and it all worked. The GitHub Action log is below. How can I troubleshoot the issue?

https://gist.github.com/dfinke/3c0d7d896a9a40809497b14d6b9e1796

**Comment by sdras** [comment]
Just so I can help debug, did you add the secrets necessary and update the env variables? Mine won't work for you out of the box, you have to add your own.

```
secrets = ["SERVICE_PASS"]
  env = {
    SERVICE_PRINCIPAL="http://sdrasAzureAction",
    TENANT_ID="72f988bf-86f1-41af-91ab-2d7cd011db47",
    APPID="sdrasAzureAction"
  }
```

**Comment by dfinke** [comment]
Yes, I set up my own SP etc. Used that also in my local deploy test.

**Comment by sdras** [comment]
Ok, that gives me a place to start. I can try to take a look in the next couple of days. I have the flu so it might be a minute here.

**Comment by dfinke** [comment]
No rush. Was hoping you may know of a log on the Azure side that I could look at.

I'll keep digging.

**Comment by sdras** [comment]
Oh! One thing I forgot to mention and need to put in the readme is that this repo houses a file called `web.config`, and you absolutely need that in order to deploy. Can you please double check that you have that file as well?

**Comment by sdras** [comment]
Haven't heard back so I'm going to close this out, please feel free to reopen if you have any more info!
