### ISSUE TITLE
Use Azure actions

### ISSUE THREAD

**Issue by piranna** [sdras/example-azure-node#2]
What about updating the repo to use the oficial [Azure actions](https://github.com/Azure/github-actions) instead of your custom one? This way it would not need to have the action defined in the repo itself :-) If it was done this way for educational purposses about how to create an action, maybe it make sense to do what I say in a different repo?

**Comment by sdras** [comment]
Mine was actually created first, when there were none- mine were released Oct 16, the Azure official ones weren't released until Nov 24. There was a month and a half where mine was the only action that fully deployed to Azure and didn't just set up a service.

**Comment by piranna** [comment]
Yes, I know, that's why I ask it would be good to update the repo to the latest official Actions, what do you think?
